#------- XADC
#ain15 (A1)
#ain16 (A0)

#VAUXP4 (Ain15p / A1) > G3
#VAUXN4 (GND / Ain15n) > G2

#VAUXP12 (Ain16p / A0) > H2
#VAUXN12 (GND / Ain16n) > J2

set_property PACKAGE_PIN H2 [get_ports vauxp12]
set_property PACKAGE_PIN J2 [get_ports vauxn12]
set_property PACKAGE_PIN G3 [get_ports vauxp4]
set_property PACKAGE_PIN G2 [get_ports vauxn4]


set_property IOSTANDARD LVCMOS33 [get_ports vauxp4]
set_property IOSTANDARD LVCMOS33 [get_ports vauxn4]
set_property IOSTANDARD LVCMOS33 [get_ports vauxp12]
set_property IOSTANDARD LVCMOS33 [get_ports vauxn12]

#------- TEST
# pin26, PIO26
set_property PACKAGE_PIN R3 [get_ports test]
set_property IOSTANDARD LVCMOS33 [get_ports test]

#------- SPI

set_property PACKAGE_PIN R2 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]

set_property PACKAGE_PIN T1 [get_ports cs_l]
set_property IOSTANDARD LVCMOS33 [get_ports cs_l]

set_property PACKAGE_PIN T2 [get_ports sclk]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]

#------- OTHER

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

create_clock -period 83.330 -name clk -waveform {0.000 41.665} [get_ports clk]
set_property PACKAGE_PIN L17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN B18 [get_ports reset_h]
set_property IOSTANDARD LVCMOS33 [get_ports reset_h]

set_property PACKAGE_PIN J17 [get_ports serial_in]
set_property IOSTANDARD LVCMOS33 [get_ports serial_in]
set_property PACKAGE_PIN J18 [get_ports serial_out]
set_property IOSTANDARD LVCMOS33 [get_ports serial_out]

set_property PACKAGE_PIN U1 [get_ports sda]
set_property PACKAGE_PIN W2 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property PULLUP true [get_ports sda]
set_property PULLUP true [get_ports scl]

set_property PACKAGE_PIN P1 [get_ports r]
set_property PACKAGE_PIN N2 [get_ports g]
set_property PACKAGE_PIN N1 [get_ports b]
set_property PACKAGE_PIN P3 [get_ports hs]
set_property PACKAGE_PIN M2 [get_ports vs]
set_property IOSTANDARD LVCMOS33 [get_ports r]
set_property IOSTANDARD LVCMOS33 [get_ports g]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports hs]
set_property IOSTANDARD LVCMOS33 [get_ports vs]

set_property IOSTANDARD LVCMOS33 [get_ports {io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[31]}]

set_property PACKAGE_PIN V8 [get_ports {io[31]}]
set_property PACKAGE_PIN U8 [get_ports {io[30]}]
set_property PACKAGE_PIN W7 [get_ports {io[29]}]
set_property PACKAGE_PIN U7 [get_ports {io[28]}]
set_property PACKAGE_PIN U3 [get_ports {io[27]}]
set_property PACKAGE_PIN W6 [get_ports {io[26]}]
set_property PACKAGE_PIN U2 [get_ports {io[25]}]
set_property PACKAGE_PIN U5 [get_ports {io[24]}]
set_property PACKAGE_PIN W4 [get_ports {io[23]}]
set_property PACKAGE_PIN V5 [get_ports {io[22]}]
set_property PACKAGE_PIN U4 [get_ports {io[21]}]
set_property PACKAGE_PIN V4 [get_ports {io[20]}]
set_property PACKAGE_PIN W5 [get_ports {io[19]}]
set_property PACKAGE_PIN V3 [get_ports {io[18]}]
set_property PACKAGE_PIN W3 [get_ports {io[17]}]
set_property PACKAGE_PIN V2 [get_ports {io[16]}]
set_property PACKAGE_PIN N3 [get_ports {io[15]}]
set_property PACKAGE_PIN M1 [get_ports {io[14]}]
set_property PACKAGE_PIN L2 [get_ports {io[13]}]
set_property PACKAGE_PIN L1 [get_ports {io[12]}]
set_property PACKAGE_PIN K2 [get_ports {io[11]}]
set_property PACKAGE_PIN J1 [get_ports {io[10]}]
set_property PACKAGE_PIN J3 [get_ports {io[9]}]
set_property PACKAGE_PIN A14 [get_ports {io[8]}]
set_property PACKAGE_PIN B15 [get_ports {io[7]}]
set_property PACKAGE_PIN A15 [get_ports {io[6]}]
set_property PACKAGE_PIN H1 [get_ports {io[5]}]
set_property PACKAGE_PIN C15 [get_ports {io[4]}]
set_property PACKAGE_PIN K3 [get_ports {io[3]}]
set_property PACKAGE_PIN A16 [get_ports {io[2]}]
set_property PACKAGE_PIN L3 [get_ports {io[1]}]
set_property PACKAGE_PIN M3 [get_ports {io[0]}]

set_property PULLDOWN true [get_ports {io[31]}]
set_property PULLDOWN true [get_ports {io[30]}]
set_property PULLDOWN true [get_ports {io[29]}]
set_property PULLDOWN true [get_ports {io[28]}]
set_property PULLDOWN true [get_ports {io[27]}]
set_property PULLDOWN true [get_ports {io[26]}]
set_property PULLDOWN true [get_ports {io[25]}]
set_property PULLDOWN true [get_ports {io[24]}]
set_property PULLDOWN true [get_ports {io[23]}]
set_property PULLDOWN true [get_ports {io[22]}]
set_property PULLDOWN true [get_ports {io[21]}]
set_property PULLDOWN true [get_ports {io[20]}]
set_property PULLDOWN true [get_ports {io[19]}]
set_property PULLDOWN true [get_ports {io[18]}]
set_property PULLDOWN true [get_ports {io[17]}]
set_property PULLDOWN true [get_ports {io[16]}]
set_property PULLDOWN true [get_ports {io[15]}]
set_property PULLDOWN true [get_ports {io[14]}]
set_property PULLDOWN true [get_ports {io[13]}]
set_property PULLDOWN true [get_ports {io[12]}]
set_property PULLDOWN true [get_ports {io[11]}]
set_property PULLDOWN true [get_ports {io[10]}]
set_property PULLDOWN true [get_ports {io[9]}]
set_property PULLDOWN true [get_ports {io[8]}]
set_property PULLDOWN true [get_ports {io[7]}]
set_property PULLDOWN true [get_ports {io[6]}]
set_property PULLDOWN true [get_ports {io[5]}]
set_property PULLDOWN true [get_ports {io[4]}]
set_property PULLDOWN true [get_ports {io[3]}]
set_property PULLDOWN true [get_ports {io[2]}]
set_property PULLDOWN true [get_ports {io[1]}]
set_property PULLDOWN true [get_ports {io[0]}]

set_property DRIVE 8 [get_ports {io[31]}]
set_property DRIVE 8 [get_ports {io[30]}]
set_property DRIVE 8 [get_ports {io[29]}]
set_property DRIVE 8 [get_ports {io[28]}]
set_property DRIVE 8 [get_ports {io[27]}]
set_property DRIVE 8 [get_ports {io[26]}]
set_property DRIVE 8 [get_ports {io[25]}]
set_property DRIVE 8 [get_ports {io[24]}]
set_property DRIVE 8 [get_ports {io[23]}]
set_property DRIVE 8 [get_ports {io[22]}]
set_property DRIVE 8 [get_ports {io[21]}]
set_property DRIVE 8 [get_ports {io[20]}]
set_property DRIVE 8 [get_ports {io[19]}]
set_property DRIVE 8 [get_ports {io[18]}]
set_property DRIVE 8 [get_ports {io[17]}]
set_property DRIVE 8 [get_ports {io[16]}]
set_property DRIVE 8 [get_ports {io[15]}]
set_property DRIVE 8 [get_ports {io[14]}]
set_property DRIVE 8 [get_ports {io[13]}]
set_property DRIVE 8 [get_ports {io[12]}]
set_property DRIVE 8 [get_ports {io[11]}]
set_property DRIVE 8 [get_ports {io[10]}]
set_property DRIVE 8 [get_ports {io[9]}]
set_property DRIVE 8 [get_ports {io[8]}]
set_property DRIVE 8 [get_ports {io[7]}]
set_property DRIVE 8 [get_ports {io[6]}]
set_property DRIVE 8 [get_ports {io[5]}]
set_property DRIVE 8 [get_ports {io[4]}]
set_property DRIVE 8 [get_ports {io[3]}]
set_property DRIVE 8 [get_ports {io[2]}]
set_property DRIVE 8 [get_ports {io[1]}]
set_property DRIVE 8 [get_ports {io[0]}]

set_property SLEW SLOW [get_ports {io[31]}]
set_property SLEW SLOW [get_ports {io[30]}]
set_property SLEW SLOW [get_ports {io[29]}]
set_property SLEW SLOW [get_ports {io[28]}]
set_property SLEW SLOW [get_ports {io[27]}]
set_property SLEW SLOW [get_ports {io[26]}]
set_property SLEW SLOW [get_ports {io[25]}]
set_property SLEW SLOW [get_ports {io[24]}]
set_property SLEW SLOW [get_ports {io[23]}]
set_property SLEW SLOW [get_ports {io[22]}]
set_property SLEW SLOW [get_ports {io[21]}]
set_property SLEW SLOW [get_ports {io[20]}]
set_property SLEW SLOW [get_ports {io[19]}]
set_property SLEW SLOW [get_ports {io[18]}]
set_property SLEW SLOW [get_ports {io[17]}]
set_property SLEW SLOW [get_ports {io[16]}]
set_property SLEW SLOW [get_ports {io[15]}]
set_property SLEW SLOW [get_ports {io[14]}]
set_property SLEW SLOW [get_ports {io[13]}]
set_property SLEW SLOW [get_ports {io[12]}]
set_property SLEW SLOW [get_ports {io[11]}]
set_property SLEW SLOW [get_ports {io[10]}]
set_property SLEW SLOW [get_ports {io[9]}]
set_property SLEW SLOW [get_ports {io[8]}]
set_property SLEW SLOW [get_ports {io[7]}]
set_property SLEW SLOW [get_ports {io[6]}]
set_property SLEW SLOW [get_ports {io[5]}]
set_property SLEW SLOW [get_ports {io[4]}]
set_property SLEW SLOW [get_ports {io[3]}]
set_property SLEW SLOW [get_ports {io[2]}]
set_property SLEW SLOW [get_ports {io[1]}]
set_property SLEW SLOW [get_ports {io[0]}]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
